"""empty message

Revision ID: 765fbdb0a328
Revises: 
Create Date: 2023-05-19 00:30:18.516748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765fbdb0a328'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('last_activity')

    # ### end Alembic commands ###
